export const GET_AUTHORS_SUCCESS = 'GET_AUTHORS_SUCCESS';
export const GET_AUTHORS_FAILURE = 'GET_AUTHORS_FAILURE';
export const GET_AUTHORS = 'GET_AUTHORS';
export const GET_CURRENT_AUTHOR_SUCCESS = 'GET_CURRENT_AUTHOR_SUCCESS';
export const GET_CURRENT_AUTHOR_FAILURE = 'GET_CURRENT_AUTHOR_FAILURE';
export const GET_CURRENT_AUTHOR = 'GET_CURRENT_AUTHOR';
