export const GET_COMMENTS_BY_BOOK_SUCCESS = 'GET_COMMENTS_BY_BOOK_SUCCESS';
export const GET_COMMENTS_BY_BOOK_FAILURE = 'GET_COMMENTS_BY_BOOK_FAILURE';
export const GET_COMMENTS_BY_BOOK = 'GET_COMMENTS_BY_BOOK';
export const ADD_COMMENT = 'ADD_COMMENT';
export const SET_COMMENTS_LIKES = 'SET_COMMENTS_LIKES';
export const GET_COMMENTS_LIKES_SUCCESS = 'GET_COMMENTS_LIKES_SUCCESS';
export const GET_COMMENTS_LIKES_FAILURE = 'GET_COMMENTS_LIKES_FAILURE';
export const GET_COMMENTS_LIKES = 'GET_COMMENTS_LIKES';
