export const GET_COMMENTS_BY_BOOK_SUCCESS = 'GET_COMMENTS_BY_BOOK_SUCCESS';
export const GET_COMMENTS_BY_BOOK_FAILURE = 'GET_COMMENTS_BY_BOOK_FAILURE';
export const GET_COMMENTS_BY_BOOK = 'GET_COMMENTS_BY_BOOK';
export const ADD_COMMENT = 'ADD_COMMENT';
