export const SHOW_LOGIN_FORM = 'SHOW_LOGIN_FORM';
export const HIDE_LOGIN_FORM = 'HIDE_LOGIN_FORM';
export const SHOW_SIGNUP_FORM = 'SHOW_SIGNUP_FORM';
export const HIDE_SIGNUP_FORM = 'HIDE_SIGNUP_FORM';
