export const SET_CURRENT_NUMBER_SUCCESS = 'SET_CURRENT_NUMBER_SUCCESS';
export const SET_CURRENT_NUMBER_FAILURE = 'SET_CURRENT_NUMBER_FAILURE';
export const SET_CURRENT_NUMBER = 'SET_CURRENT_NUMBER';
